=== hmrc/apprenticeship-levy/public/api/conf/1.0/schemas/get-employer-details.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Get employer's details",
  "type": "object",
  "properties": {
    "_links": {
      "type": "object",
      "properties": {
        "fractions": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string",
              "description": "The relative link to fetch English percentage for this employer reference",
              "example": "/epaye/123%2FAB12345/fractions"
            }
          }
        },
        "declarations": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string",
              "description": "The relative link to fetch levy declarations for this employer reference",
              "example": "/epaye/123%2FAB12345/declarations"
            }
          }
        },
        "employment-check": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string",
              "description": "The relative link to fetch employee employment status for this employer reference",
              "example": "/epaye/123%2FAB12345/employed/{nino}"
            }
          }
        },
        "self": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string",
              "description": "The relative link to fetch contact details this employer reference",
              "example": "/epaye/123%2FAB12345"
            }
          }
        }
      }
    },
    "empref": {
      "type": "string",
      "optional": true,
      "description": "The PAYE Reference for the employer. This will be the same as provided in the URL.",
      "example": "123/AB12345"
    },
    "employer": {
      "type": "object",
      "optional": true,
      "properties": {
        "name": {
          "type": "object",
          "properties": {
            "nameLine1": {
              "type": "string",
              "optional": true,
              "description": "The first line of the employer's name",
              "example": "KILL-JOY PLC THE FUNERAL"
            },
            "nameLine2": {
              "type": "string",
              "optional": true,
              "description": "The second line of the employer's name",
              "example": "COMPANY"
            }
          }
        },
        "address": {
          "type": "object",
          "optional": true,
          "properties": {
            "addressLine1": {
              "type": "string",
              "optional": true,
              "description": "The first line of the employer's address",
              "example": "Foreign Address Line 1"
            },
            "addressLine2": {
              "type": "string",
              "optional": true,
              "description": "The second line of the employer's address",
              "example": "Foreign Address Line 2"
            },
            "addressLine3": {
              "type": "string",
              "optional": true,
              "description": "The third line of the employer's address",
              "example": "Foreign Address Line 3"
            },
            "addressLine4": {
              "type": "string",
              "optional": true,
              "description": "The forth line of the employer's address",
              "example": "Foreign Address Line 4"
            },
            "addressLine5": {
              "type": "string",
              "optional": true,
              "description": "The fifth line of the employer's address",
              "example": "Foreign Address Line 5"
            },
            "postcode": {
              "type": "string",
              "optional": true,
              "description": "The fifth line of the employer's address",
              "example": "NE30 4XX"
            },
            "foreignCountry": {
              "type": "string",
              "optional": true,
              "description": "The country of the employer's address",
              "example": "France"
            }
          }
        },
        "contact": {
          "type": "object",
          "optional": true,
          "properties": {
            "telephone": {
              "type": "object",
              "optional": true,
              "properties": {
                "telephoneNumber": {
                  "type": "string",
                  "optional": true,
                  "description": "The employer's main contact telephone number",
                  "example": "0123 456789"
                },
                "fax": {
                  "type": "string",
                  "optional": true,
                  "description": "The employer's main contact telephone number",
                  "example": "0123 456789"
                }
              }
            },
            "email": {
              "type": "object",
              "optional": true,
              "properties": {
                "primary": {
                  "type": "string",
                  "optional": true,
                  "description": "The fifth line of the employer's address",
                  "example": "someone@hmrc.gov.uk"
                }
              }
            }
          }
        }
      }
    },
    "communication": {
      "type": "object",
      "optional": true,
      "properties": {
        "name": {
          "type": "object",
          "properties": {
            "nameLine1": {
              "type": "string",
              "optional": true,
              "description": "The first line of the employer's name",
              "example": "KILL-JOY PLC THE FUNERAL"
            },
            "nameLine2": {
              "type": "string",
              "optional": true,
              "description": "The second line of the employer's name",
              "example": "COMPANY"
            }
          }
        },
        "address": {
          "type": "object",
          "optional": true,
          "properties": {
            "addressLine1": {
              "type": "string",
              "optional": true,
              "description": "The first line of the employer's address",
              "example": "Foreign Address Line 1"
            },
            "addressLine2": {
              "type": "string",
              "optional": true,
              "description": "The second line of the employer's address",
              "example": "Foreign Address Line 2"
            },
            "addressLine3": {
              "type": "string",
              "optional": true,
              "description": "The third line of the employer's address",
              "example": "Foreign Address Line 3"
            },
            "addressLine4": {
              "type": "string",
              "optional": true,
              "description": "The forth line of the employer's address",
              "example": "Foreign Address Line 4"
            },
            "addressLine5": {
              "type": "string",
              "optional": true,
              "description": "The fifth line of the employer's address",
              "example": "Foreign Address Line 5"
            },
            "postcode": {
              "type": "string",
              "optional": true,
              "description": "The fifth line of the employer's address",
              "example": "NE30 4XX"
            },
            "foreignCountry": {
              "type": "string",
              "optional": true,
              "description": "The country of the employer's address",
              "example": "France"
            }
          }
        },
        "contact": {
          "type": "object",
          "optional": true,
          "properties": {
            "telephone": {
              "type": "object",
              "optional": true,
              "properties": {
                "telephoneNumber": {
                  "type": "string",
                  "optional": true,
                  "description": "The employer's main contact telephone number",
                  "example": "0123 456789"
                },
                "fax": {
                  "type": "string",
                  "optional": true,
                  "description": "The employer's main contact telephone number",
                  "example": "0123 456789"
                }
              }
            },
            "email": {
              "type": "object",
              "optional": true,
              "properties": {
                "primary": {
                  "type": "string",
                  "optional": true,
                  "description": "The fifth line of the employer's address",
                  "example": "someone@hmrc.gov.uk"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== hmrc/apprenticeship-levy/ac/resources/staging/sandbox/empref/840MODES17.json
{
  "_links": {
    "declarations": {
      "href": "/epaye/840%2FMODES17/declarations"
    },
    "employment-check": {
      "href": "/epaye/840%2FMODES17/employed/{nino}"
    },
    "fractions": {
      "href": "/epaye/840%2FMODES17/fractions"
    },
    "self": {
      "href": "/epaye/840%2FMODES17"
    }
  },
  "communication": {
    "address": {
      "addressLine1": "Foreign Address Line 1",
      "addressLine2": "Foreign Address Line 2",
      "addressLine3": "Foreign Address Line 3",
      "addressLine4": "Foreign Address Line 4",
      "addressLine5": "Foreign Address Line 5",
      "foreignCountry": "France",
      "postcode": "NE30 4XX"
    },
    "contact": {
      "email": {
        "primary": "someone@hmrc.gov.uk"
      },
      "telephone": {
        "telephoneNumber": "0123 456789"
      }
    },
    "name": {
      "nameLine1": "KILL-JOY PLC THE FUNERAL",
      "nameLine2": "COMPANY"
    }
  },
  "employer": {
    "address": {
      "addressLine1": "Foreign Address Line 1",
      "addressLine2": "Foreign Address Line 2",
      "addressLine3": "Foreign Address Line 3",
      "addressLine4": "Foreign Address Line 4",
      "addressLine5": "Foreign Address Line 5",
      "foreignCountry": "France"
    },
    "contact": {
      "email": {},
      "telephone": {}
    },
    "name": {
      "nameLine1": "KILL-JOY PLC THE FUNERAL",
      "nameLine2": "COMPANY"
    }
  },
  "empref": "840/MODES17"
}

=== hmrc/apprenticeship-levy/ac/resources/live/sandbox/empref/840MODES17.json
{
  "_links": {
    "fractions": {
      "href": "/sandbox/epaye/840%2FMODES17/fractions"
    },
    "declarations": {
      "href": "/sandbox/epaye/840%2FMODES17/declarations"
    },
    "employment-check": {
      "href": "/sandbox/epaye/840%2FMODES17/employed/{nino}"
    },
    "self": {
      "href": "/sandbox/epaye/840%2FMODES17"
    }
  },
  "empref": "840/MODES17",
  "employer": {
    "name": {
      "nameLine1": "KILL-JOY PLC THE FUNERAL",
      "nameLine2": "COMPANY"
    },
    "address": {
      "addressLine1": "Foreign Address Line 1",
      "addressLine2": "Foreign Address Line 2",
      "addressLine3": "Foreign Address Line 3",
      "addressLine4": "Foreign Address Line 4",
      "addressLine5": "Foreign Address Line 5",
      "foreignCountry": "France"
    },
    "contact": {
      "telephone": {},
      "email": {}
    }
  },
  "communication": {
    "name": {
      "nameLine1": "KILL-JOY PLC THE FUNERAL",
      "nameLine2": "COMPANY"
    },
    "address": {
      "addressLine1": "Foreign Address Line 1",
      "addressLine2": "Foreign Address Line 2",
      "addressLine3": "Foreign Address Line 3",
      "addressLine4": "Foreign Address Line 4",
      "addressLine5": "Foreign Address Line 5",
      "postcode": "NE30 4XX",
      "foreignCountry": "France"
    },
    "contact": {
      "telephone": {
        "telephoneNumber": "0123 456789"
      },
      "email": {
        "primary": "someone@hmrc.gov.uk"
      }
    }
  }
}

=== hmrc/apprenticeship-levy/ac/resources/qa/sandbox/empref/840MODES17.json
{
  "_links": {
    "fractions": {
      "href": "/epaye/840%2FMODES17/fractions"
    },
    "declarations": {
      "href": "/epaye/840%2FMODES17/declarations"
    },
    "employment-check": {
      "href": "/epaye/840%2FMODES17/employed/{nino}"
    },
    "self": {
      "href": "/epaye/840%2FMODES17"
    }
  },
  "empref": "840/MODES17",
  "employer": {
    "name": {
      "nameLine1": "KILL-JOY PLC THE FUNERAL",
      "nameLine2": "COMPANY"
    },
    "address": {
      "addressLine1": "Foreign Address Line 1",
      "addressLine2": "Foreign Address Line 2",
      "addressLine3": "Foreign Address Line 3",
      "addressLine4": "Foreign Address Line 4",
      "addressLine5": "Foreign Address Line 5",
      "foreignCountry": "France"
    },
    "contact": {
      "telephone": {},
      "email": {}
    }
  },
  "communication": {
    "name": {
      "nameLine1": "KILL-JOY PLC THE FUNERAL",
      "nameLine2": "COMPANY"
    },
    "address": {
      "addressLine1": "Foreign Address Line 1",
      "addressLine2": "Foreign Address Line 2",
      "addressLine3": "Foreign Address Line 3",
      "addressLine4": "Foreign Address Line 4",
      "addressLine5": "Foreign Address Line 5",
      "foreignCountry": "France"
    },
    "contact": {
      "telephone": {},
      "email": {}
    }
  }
}
